// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPvMWIS_W88T2zSkfnWMtLm_gCMZIKSFc',
    appId: '1:511166861660:web:bb7e3fb381c90a9217f199',
    messagingSenderId: '511166861660',
    projectId: 'travelapptest-e03a8',
    authDomain: 'travelapptest-e03a8.firebaseapp.com',
    storageBucket: 'travelapptest-e03a8.appspot.com',
    measurementId: 'G-89Z78Z50KN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmCiQDfFqZZwG4BEBntjGTxlsNhLcVqao',
    appId: '1:511166861660:android:db6ec65b991b573917f199',
    messagingSenderId: '511166861660',
    projectId: 'travelapptest-e03a8',
    storageBucket: 'travelapptest-e03a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-CUJbjKClJA-cOexB6qX8bXMtFpxBeWY',
    appId: '1:511166861660:ios:64a4c400e57098e917f199',
    messagingSenderId: '511166861660',
    projectId: 'travelapptest-e03a8',
    storageBucket: 'travelapptest-e03a8.appspot.com',
    androidClientId: '511166861660-l96r779plsf5h3iut4phej70nlsv5isn.apps.googleusercontent.com',
    iosClientId: '511166861660-3rhc4p0ulup2o13e1siutosii8orl878.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelapptest',
  );
}
